x = int(input('Digite um numero: '))
print('------ TABUADA DO {} ------'.format(x))
x1 = x * 1
x2 = x * 2
x3 = x * 3
x4 = x * 4
x5 = x * 5
x6 = x * 6
x7 = x * 7
x8 = x * 8
x9 = x * 9
x10 = x * 10
print('{} * 1 = {}'.format(x, x1))
print('{} * 2 = {}'.format(x, x2))
print('{} * 3 = {}'.format(x, x3))
print('{} * 4 = {}'.format(x, x4))
print('{} * 5 = {}'.format(x, x5))
print('{} * 6 = {}'.format(x, x6))
print('{} * 7 = {}'.format(x, x7))
print('{} * 8 = {}'.format(x, x8))
print('{} * 9 = {}'.format(x, x9))
print('{} * 10 = {}'.format(x, x10))
