w = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(w))
print('Só tem espaços', w.isspace())
print('É um numerico', w.isnumeric())
print('É alfabetico', w.isalpha())
print('É alfanumerico', w.isalnum())
print('Esta em maisculo', w.isupper())
print('Esta em minusculo', w.islower())
print('Está capitalizado', w.istitle())
